package io.openfactory.api.workpack;

import io.openfactory.api.box.model.Box;
import io.openfactory.api.brief.model.Brief;
import io.openfactory.api.handoff.model.Handoff;
import io.openfactory.api.plan.model.ExecutionPlanEntity;
import io.openfactory.api.workpack.model.Workpack;
import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.StreamingOutput;

import java.io.IOException;
import java.util.List;
import java.util.UUID;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Path("/api/workpacks/{id}/download")
public class PackageDownloadResource {

    @Inject
    WorkpackService workpackService;

    @GET
    @Produces("application/zip")
    public Response download(@PathParam("id") UUID id) {
        Workpack w        = workpackService.findById(id);
        Brief brief       = Brief.findByWorkpack(w.id);
        List<Box> boxes   = Box.list("workpack.id = ?1 order by orderIndex", w.id);
        ExecutionPlanEntity plan = ExecutionPlanEntity.findByWorkpack(w.id);
        Handoff handoff   = Handoff.findByWorkpack(w.id);

        String filename = slugify(w.title) + "-package.zip";

        StreamingOutput stream = out -> {
            try (ZipOutputStream zip = new ZipOutputStream(out)) {
                addEntry(zip, "README.md",   buildReadme(w));
                if (brief   != null) addEntry(zip, "brief.md",    buildBrief(brief));
                if (plan    != null) addEntry(zip, "plan.json",   plan.steps != null ? plan.steps : "[]");
                if (handoff != null) addEntry(zip, "handoff.md",  buildHandoff(handoff));
                for (int i = 0; i < boxes.size(); i++) {
                    String name = String.format("boxes/%02d-%s.md", i + 1, slugify(boxes.get(i).title));
                    addEntry(zip, name, buildBox(boxes.get(i)));
                }
            } catch (IOException e) {
                throw new RuntimeException("Failed to build ZIP", e);
            }
        };

        return Response.ok(stream)
            .header("Content-Disposition", "attachment; filename=\"" + filename + "\"")
            .type("application/zip")
            .build();
    }

    // -----------------------------------------------------------------------

    private String buildReadme(Workpack w) {
        return "# " + w.title + "\n\n" +
               "**Stage:** " + w.stage + "\n" +
               "**ID:** " + w.id + "\n\n" +
               "This package was generated by openFactory.\n\n" +
               "## Contents\n\n" +
               "- `brief.md` — project brief\n" +
               "- `boxes/` — work boxes with instructions\n" +
               "- `plan.json` — execution plan steps\n" +
               "- `handoff.md` — handoff notes\n";
    }

    private String buildBrief(Brief b) {
        return "# Brief: " + nvl(b.title) + "\n\n" +
               "## Main Idea\n\n" + nvl(b.mainIdea) + "\n\n" +
               "## Objective\n\n" + nvl(b.objective) + "\n\n" +
               "## Actors\n\n```json\n" + nvl(b.actors) + "\n```\n\n" +
               "## Scope\n\n**Includes:**\n```json\n" + nvl(b.scopeIncludes) + "\n```\n\n" +
               "**Excludes:**\n```json\n" + nvl(b.scopeExcludes) + "\n```\n\n" +
               "## Constraints\n\n```json\n" + nvl(b.constraints) + "\n```\n\n" +
               "## Success Criteria\n\n```json\n" + nvl(b.successCriteria) + "\n```\n\n" +
               "## Domain Facts\n\n```json\n" + nvl(b.domainFacts) + "\n```\n";
    }

    private String buildBox(Box box) {
        return "# Box: " + box.title + "\n\n" +
               "**Node ID:** " + nvl(box.nodeId) + "\n" +
               "**Order:** " + box.orderIndex + "\n" +
               "**Status:** " + box.status + "\n\n" +
               "## Purpose\n\n" + nvl(box.purpose) + "\n\n" +
               "## Input Context\n\n" + nvl(box.inputContext) + "\n\n" +
               "## Expected Output\n\n" + nvl(box.expectedOutput) + "\n\n" +
               "## Instructions\n\n```json\n" + nvl(box.instructions) + "\n```\n\n" +
               "## Constraints\n\n```json\n" + nvl(box.constraints) + "\n```\n\n" +
               "## Dependencies\n\n```json\n" + nvl(box.dependencies) + "\n```\n\n" +
               "## Acceptance Criteria\n\n```json\n" + nvl(box.acceptanceCriteria) + "\n```\n\n" +
               "## Handoff Notes\n\n" + nvl(box.handoff) + "\n";
    }

    private String buildHandoff(Handoff h) {
        return "# Handoff\n\n" +
               "**Approval Status:** " + h.approvalStatus + "\n\n" +
               "## Notes\n\n" + nvl(h.handoffNotes) + "\n\n" +
               "## Assumptions\n\n```json\n" + nvl(h.assumptions) + "\n```\n\n" +
               (h.reviewNotes != null && !h.reviewNotes.isBlank()
                   ? "## Review Notes\n\n" + h.reviewNotes + "\n" : "");
    }

    private void addEntry(ZipOutputStream zip, String name, String content) throws IOException {
        zip.putNextEntry(new ZipEntry(name));
        zip.write(content.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        zip.closeEntry();
    }

    private String slugify(String s) {
        if (s == null) return "untitled";
        return s.toLowerCase()
                .replaceAll("[^a-z0-9]+", "-")
                .replaceAll("^-|-$", "");
    }

    private String nvl(String s) {
        return s != null ? s : "";
    }
}
